export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "United States": "US",
  "United Kingdom": "GB",
  "Canada": "CA",
  "Australia": "AU",
  "Germany": "DE",
  "France": "FR",
  "Netherlands": "NL",
  "Pakistan": "PK",
  "India": "IN",
  "United Arab Emirates": "AE",
  "Saudi Arabia": "SA",
  "Brazil": "BR",
  "Mexico": "MX",
  "Spain": "ES",
  "Italy": "IT",
  "Japan": "JP",
  "South Korea": "KR",
  "Singapore": "SG",
  "Sweden": "SE",
  "Norway": "NO",
  "Denmark": "DK",
  "Switzerland": "CH",
  "Belgium": "BE",
  "Ireland": "IE",
  "New Zealand": "NZ",
  "South Africa": "ZA",
  "Turkey": "TR",
  "Poland": "PL",
  "Portugal": "PT",
  "Austria": "AT",
  "Finland": "FI",
  "Israel": "IL",
  "Egypt": "EG",
  "Nigeria": "NG",
  "Philippines": "PH",
  "Indonesia": "ID",
  "Malaysia": "MY",
  "Thailand": "TH",
  "Vietnam": "VN",
  "Argentina": "AR",
  "Colombia": "CO",
  "Chile": "CL",
  "Latvia": "LV",
  "Kosovo": "XK",
  "Cyprus": "CY",
}
